name: Deploy all back-end services

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment name for the stack. Only lower-case and no spaces!
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-common-service:
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      service-name: common-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-user-service:
    needs: deploy-common-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      service-name: user-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-card-service:
    needs: deploy-user-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      service-name: card-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-collection-service:
    needs: deploy-user-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      service-name: collection-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-deck-service:
    needs: deploy-user-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      service-name: deck-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-wishlist-service:
    needs: deploy-user-service
    uses: ./.github/workflows/release-back-end-pipeline.yml
    with:
      service-name: wishlist-service
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
